import Head from "next/head";
import Navbar from "@/components/Navbar/Navbar";
import SocialMedia from "@/components/SocialMedia/SocialMedia";
import styles from "@/styles/Home.module.css";

import Footer from "@/components/Footer/Footer";
const WebsiteLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} relative`}>
        <SocialMedia />
        {children}
      </main>
      <Footer />
    </>
  );
};

export default WebsiteLayout;
